# Generated by Django 2.1.11 on 2019-08-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutineChangeDetector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='classified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
