# Generated by Django 2.1.11 on 2019-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutineChangeDetector', '0002_userdata_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroutine',
            name='timestamp',
            field=models.BigIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
