# Generated by Django 2.1.11 on 2019-08-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutineChangeDetector', '0002_auto_20190816_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroutine',
            name='anomaly',
            field=models.BooleanField(null=True),
        ),
    ]
